# Generated by Django 3.0.8 on 2020-08-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyMaterial', '0002_auto_20200801_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='patterns',
        ),
        migrations.AddField(
            model_name='pre_q_paper',
            name='Subject_Name',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_q_paper',
            name='patterns',
            field=models.CharField(choices=[('2015', '2015'), ('2019', '2019')], default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pre_q_paper',
            name='Subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyMaterial.Subject'),
        ),
    ]
